FORMAT: 1A
HOST: https://api.acme.com

# ACME API

API requires authorization. All requests must have valid `auth_token`


# Group asd123


## asd123 [/api/post]

### 123asd [POST]




+ Parameters

+ Request json

  + Headers
    content-type: application/json


+ Response 200

  + Headers
    content-type: application/json; charset=utf-8
    cache-control: max-age=0, private, must-revalidate
    x-request-id: 1v5oadijobr2b8ccq54toahdqcrf67fl


# Group testttasd


## testttasd [/api/test/{p}]

### Testiiii [GET]




+ Parameters

+ Request json

  + Headers


+ Response 200

  + Headers
    content-type: application/json; charset=utf-8
    cache-control: max-age=0, private, must-revalidate
    x-request-id: nb74m6kh94l2or9a78amaat7clmk51no


